[package]
description = "Arc Main"
edition = "2021"
license = "GPL-3.0-only"
name = "arcboot_main"
version = "0.1.1"

[workspace]
members = ["export", "arcboot"]

[dependencies]
arcboot = { path = "arcboot", features = ["builtin_allocator"] }
arcboot_api = { path = "export", optional = true }
log = { version = "0.4.11", default-features = false }
# some problems with reexporting
uefi = { version = "0.16.0", features = ["exts"] }
uefi-macros = { version = "0.7.0" }

[features]
api = ["arcboot_api"]
uefi_support = []
