[package]
name = "arcboot"
version = "0.1.1"
edition = "2021"
description = "An executable tool for building rust-based kernels and compiling, assembling and linking any extra dependencies"
license = "BSD-3-Clause"

exclude = [
    "archive/*",
    "examples/*",
    "support",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
