[package]
description = "Arc Bootloaders for RV, ARM and x86"
edition = "2021"
license = "GPL-3.0-only"
name = "arcboot"
version = "0.1.0"

[dependencies]
uefi = { version = "0.15.0", features = [
    "alloc",
    "logger",
    "exts",
], optional = true }
uefi-services = { version = "0.12.0", optional = true }
uefi-macros = { version = "0.6.1", optional = true }
acpi = { version = "4.1.0", optional = true }
embedded-hal = "0.2.7"
log = { version = "0.4.11", default-features = false }
tock-registers = "0.7.0"
goblin = { version = "0.5.1", default-features = false, features = [
    "elf64",
    "elf32",
    "archive",
    "endian_fd",
    "alloc",
] }

# ? Maybe combine uefi + load sbi ABI, then arcboot
[target.'cfg(target_arch = "riscv64")'.dependencies]
rustsbi = "0.2.2"
riscv = "0.8.0"
riscv-rt = "0.8.1"

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = "7.2.0"
aarch64 = "*"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14.9"

[features]
uefi_support = ["dep:uefi", "dep:uefi-services", "dep:uefi-macros", "dep:acpi"]
