[package]
description = "Arc Main"
edition = "2021"
license = "GPL-3.0-only"
name = "arcboot_main"
version = "0.1.1"

[workspace]
members = ["export", "arcboot"]

[dependencies]
arcboot = { path = "arcboot" }
arcboot_api = { path = "export", optional = true }

[features]
api = ["arcboot_api"]
uefi_support = []
