[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[alias]
barm = "build --target aarch64-unknown-none --release"
bx86 = "build --target=riscv64gc-unknown-none-elf --release"
#* NOTE: uefi-rs doesnt support riscv 
brv = "build --target=x86_64-unknown-none --release"
