[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true

[alias]
# pass --release or --debug. Default is --debug
barm = "build --target aarch64-unknown-uefi --features uefi_support"
barmelf = "build --target aarch64-unknown-none"
bx86 = "build --target riscv64gc-unknown-none-elf"
brv = "build --target x86_64-unknown-none"
tarm = "test --target aarch64-unknown-none --no-run"
rarm = "run --target aarch64-unknown-uefi --features uefi_support"

[build]
out-dir = "build"

[target.aarch64-unknown-uefi]
# Pass ovmf vars to qemu as well (do it with -disk or -drive)
runner = ".arcboot/run.sh"

[target.cfg.target_feature.no_uefi]
rustflags = ["-C", "link-arg=-Tbuild/aarch64/arcboot.ld"]
