[unstable]
unstable-options = true

[alias]
barm = "build --target aarch64-unknown-uefi --features uefi_support -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
bx86 = "build --target x86_64-unknown-uefi --features uefi_support"
# define our own target for riscv, maybe use arc
# brv = "build --target riscv64gc-uefi.json"
tarm = "test --target aarch64-unknown-uefi --no-run --features uefi_support"

[build]
out-dir = "build"

[test]
out-dir = "build"

[target.aarch64-unknown-uefi]
runner = ".arcboot/run.sh"

[target.cfg.target_feature.no_uefi]
rustflags = ["-C", "link-arg=-Tbuild/aarch64/arcboot.ld"]
