[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true

[alias]
# pass --release or --debug. Default is --debug
barm = "build --target aarch64-unknown-none"
bx86 = "build --target riscv64gc-unknown-none-elf"
brv = "build --target x86_64-unknown-none"
tarm = "test --target aarch64-unknown-none --no-run"

[build]
out-dir = "build"
