[unstable]
unstable-options = true

[alias]
## STANDARD

# AARCH64
barmstd = "build --bin standard --target .arcboot/aarch64/armv8.json --features arcboot,builtin_allocator -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"

## UEFI

# AARCH64
barmefi = "build --bin uefi --target aarch64-unknown-uefi --features uefi_support,builtin_allocator -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
# x86_64
bx86efi = "build --target x86_64-unknown-uefi --features uefi_support,builtin_allocator -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"

## TEST
# FOR TESTING MAIN. For testing arcboot, use cargo test in Arcboot/arcboot
t = "test --features main_test"

[build]
out-dir = "build"
